.travis.yml, composer.lock, tests/Fixtures/Symfony/TestAppKernel.php, tests/Fixtures/Symfony/app/console, tests/Server/001-swoole-server-start-response-stop.sh
It's easier to test server commands as a bash script, since swoole
creates multiple processes.
=> test(server): Add simple start, request, stop server test in bash

src/Bridge/Symfony/Bundle/Command/AbstractServerStartCommand.php, src/Bridge/Symfony/Bundle/Command/ServerReloadCommand.php, src/Bridge/Symfony/Bundle/Command/ServerStopCommand.php, src/Bridge/Symfony/Bundle/DependencyInjection/SwooleExtension.php, src/Bridge/Symfony/Bundle/Resources/config/commands.yaml, src/Bridge/Symfony/Bundle/Resources/config/services.yaml, src/Server/Configurator/ChainConfigurator.php, src/Server/Configurator/WithRequestHandler.php, src/Server/Configurator/WithServerStartHandler.php, src/Server/HttpServerFactory.php, tests/Unit/Server/Configurator/ChainConfiguratorTest.php, tests/Unit/Server/Configurator/WithRequestHandlerTest.php
Creating matrix of configuration and http server factory services when some services needs to be
only in specific commands can become quite annoying
BREAKING CHANGE:
- Server\HttpServerFactory should not be instantiated anymore, due to
removed hard coupling with ConfiguratorInterface, and `make()` method
becomig static. Now use directly: `HttpServerFactory::make()`
- Configuring server (using object implementing ConfiguratorInterface)
now happens in execute method of AbstractServerStartCommand
- Server\Configurator\ChainConfigurator now accepts
ConfiguratorInterface variadic starting from second argument and
implements IteratorAggregate retruning its configurators to ease DI usage (see
src/Bridge/Symfony/Bundle/Resources/commands.yaml)
=> refactor(di): Simplify registering configurators

tests/Server/000-list-swoole.sh
Call `console list swoole` to ensure DI configuration is proper and configure() method executes
correctly.
=> test(commands): Test console descriptions

src/Common/XdebugHandler/XdebugHandler.php
By default symfony Process has timeout 60 seconds. So if a swoole server is automatically restarted to remove XDebug it is then terminated one minute later. That wasn't intended, right?
=> Remove process timeout

.travis.yml
Ref: https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration
=> ci(travis): Migrate to VM based infrastructure

docs/configuration-reference.md, src/Bridge/Symfony/Bundle/Command/AbstractServerStartCommand.php, src/Bridge/Symfony/Bundle/Command/ServerStatusCommand.php, src/Bridge/Symfony/Bundle/DependencyInjection/Configuration.php, src/Bridge/Symfony/Bundle/DependencyInjection/SwooleExtension.php, src/Bridge/Symfony/Bundle/Resources/config/commands.yaml, src/Bridge/Symfony/Bundle/Resources/config/services.yaml, src/Client/Http.php, src/Client/HttpClient.php, src/Server/Api/ApiServer.php, src/Server/Api/ApiServerClient.php, src/Server/Api/ApiServerInterface.php, src/Server/Api/ApiServerRequestHandler.php, src/Server/Api/WithApiServerConfiguration.php, src/Server/Config/Sockets.php, src/Server/Configurator/WithHttpServerConfiguration.php, src/Server/HttpServer.php, src/Server/HttpServerConfiguration.php, src/Server/HttpServerFactory.php, tests/Feature/SwooleServerReloadCommandTest.php, tests/Feature/SwooleServerReloadViaApiClientTest.php, tests/Feature/SwooleServerReloadViaHttpApiTest.php, tests/Feature/SwooleServerRunCommandTest.php, tests/Feature/SwooleServerStartStopCommandTest.php, tests/Feature/SwooleServerStatusCommandTest.php, tests/Fixtures/Symfony/CoverageBundle/CoverageBundle.php, tests/Fixtures/Symfony/TestBundle/Test/ServerTestCase.php, tests/Fixtures/Symfony/app/config/api/swoole.yaml, tests/Fixtures/Symfony/app/config/swoole.yaml, tests/run-feature-tests-code-coverage.sh
API Server component will allow to manage Swoole HTTP Server trough HTTP interface.
Command `swoole:server:status` is added to get informations about currently running HTTP server.
Closes #2
=> feat(apiserver): Create API Server component

.dockerignore, .editorconfig, Dockerfile, src/Bridge/Symfony/Bundle/Command/ServerReloadCommand.php, src/Bridge/Symfony/Bundle/Command/ServerStartCommand.php, src/Bridge/Symfony/Bundle/Command/ServerStopCommand.php, tests/Feature/SwooleCustomPidFileTest.php, tests/Feature/SwooleServerRunCommandTest.php, tests/Feature/SwooleServerStartStopCommandTest.php, tests/Feature/SwooleServerStatusCommandTest.php, tests/Fixtures/Symfony/CoverageBundle/RequestHandler/CodeCoverageRequestHandler.php, tests/Fixtures/Symfony/TestBundle/Test/ServerTestCase.php, tests/Fixtures/resources/.gitignore
=> refactor(pid): Rename "pid_file" option to "pid-file"

src/Bridge/Symfony/Bundle/DependencyInjection/SwooleExtension.php, src/Client/Http.php, src/Client/HttpClient.php, tests/Feature/StaticFilesServingTest.php, tests/Feature/SwooleServerHMRTest.php, tests/Fixtures/Symfony/TestBundle/Test/ServerTestCase.php, tests/Fixtures/Symfony/app/config/auto/swoole.yaml, tests/Fixtures/Symfony/app/config/static/swoole.yaml
A bug caused that "AdvancedStaticFilesServer" was not tagged as bootable service, what resulted in
unsed public directory path.
=> fix(static-server): Fix unset public dir path in "AdvancedStaticFilesServer"

.editorconfig, src/Bridge/Symfony/Bundle/Command/AbstractServerStartCommand.php, src/Server/Configurator/WithServerStartHandler.php, src/Server/HttpServerConfiguration.php, src/Server/LifecycleHandler/SigIntHandler.php, tests/Feature/SwooleServerRunCommandTest.php, tests/Feature/SwooleServerStartStopCommandTest.php, tests/Fixtures/Symfony/app/config/reactor/swoole.yaml, tests/Fixtures/Symfony/app/config/swoole.yaml, tests/Unit/Server/Configurator/WithServerStartHandlerTest.php
Using `swoole:server:run` command with `reactor` running mode caused error regarding setting up signal listener on manager process.
When using `reactor` mode, swoole server event `start` cannot be used due to master process is the same as manager process. Use event `ManagerStart` instead.
=> fix(server): Make sure "reactor" running mode works correctly

.circleci/config.yml
Install deps via "npm" because "yarn" has issues with commitlint package. Install missing git
excutable.
=> ci(circle): Fix commitlint usage

CHANGELOG.md
They were added by CI script automatically. After script fixes done in PR #69 empty sections should not appear anymore.
=> docs(changelog): Clean empty sections

src/Bridge/Symfony/HttpFoundation/ResponseProcessor.php
fix(server): Use \SplFile::getRealPath for Response::sendfile Operation for a BinaryFileReponse
Sorry for reopen... some misstake with the rebase
=> fix(server): Use \SplFile::getRealPath for Response::sendfile Operation for a BinaryFileReponse 

composer.json, composer.lock
Current swoole version is 4.5.0, which is not allowed by the current constraint.
This switches to carret `^` operator to allow `>=4.4.7 & <5.0.0`
Fixes #211
=> Allow ext-swool 4.5.0

docs/configuration-reference.md, src/Bridge/Symfony/Bundle/Command/AbstractServerStartCommand.php, src/Bridge/Symfony/Bundle/DependencyInjection/Configuration.php, src/Server/HttpServerConfiguration.php
Hi @k911,
First of all, many thanks for the amazing bundle!
I needed to set the `max_request` and `max_request_grace` options from the bundle configuration so I thought of adding them.
I couldn't find any tests related to the configuration parsing and passing to Swoole, should I create one? If so, should I just test the HttpServerConfiguration class or should I also test parsing from Symfony's side?
Let me know, thanks!
=> feat(http_server): add max_request and max_request_grace configuration options

src/Bridge/Symfony/Bundle/DependencyInjection/SwooleExtension.php, src/Bridge/Symfony/ErrorHandler/ErrorResponder.php, src/Bridge/Symfony/ErrorHandler/ExceptionHandlerFactory.php, src/Bridge/Symfony/ErrorHandler/SymfonyExceptionHandler.php, src/Bridge/Symfony/ErrorHandler/ThrowableHandlerFactory.php, src/Server/RequestHandler/AdvancedStaticFilesServer.php, tests/Unit/Bridge/Symfony/ErrorHandler/ExceptionHandlerFactoryTest.php, tests/Unit/Bridge/Symfony/ErrorHandler/ThrowableHandlerFactoryTest.php
- use const in AdvancedStaticFilesServer just as it was before
=> refactor(error-handler): move to proper namespace

composer.json, composer.lock, src/Bridge/Symfony/Bundle/DependencyInjection/CompilerPass/DebugLogProcessorPass.php, src/Bridge/Symfony/Bundle/SwooleBundle.php, tests/Feature/SymfonyProfilerTest.php, tests/Fixtures/Symfony/TestAppKernel.php, tests/Fixtures/Symfony/TestBundle/Controller/TwigController.php, tests/Fixtures/Symfony/TestBundle/Test/ServerTestCase.php, tests/Fixtures/Symfony/app/config/profiler/framework.yaml, tests/Fixtures/Symfony/app/config/profiler/routing/routing.yaml, tests/Fixtures/Symfony/app/config/profiler/web_profiler.yaml, tests/Fixtures/Symfony/app/config/services.yaml, tests/Fixtures/Symfony/app/console, tests/Fixtures/Symfony/app/templates/base.html.twig
=> fix for log collecting in symfony profiler

src/Bridge/Symfony/Bundle/DependencyInjection/SwooleExtension.php
Fixes #270 
I've tested it locally using k911/swoole-bundle-symfony-demo repository by installing `composer req orm` and commenting out `doctrine.orm` configuration.
=> fix(doctrine): autoconfigure EntityManagerHandler only when orm is available in symfony's container

.circleci/release-version.sh, CHANGELOG.md
it causes troubles when `'` character is present in release notes
also, fix the changelog
Fixes #276
=> ci(release-version): do not use xargs to remove newlines

src/Bridge/Symfony/HttpFoundation/Session/SetSessionCookieEventListener.php, tests/Feature/SymfonySessionSwooleSessionStorageTest.php, tests/Fixtures/Symfony/TestAppKernel.php, tests/Fixtures/Symfony/TestCacheKernel.php
It's a good idea to reset the state regardless of the request being session related or not. There can be different reasons why session storage may get populated, while request may not contain a session.
One of the real world cases that I encountered - use of CacheKernel:
1. CacheKernel gets the original request, which will not be considered as "sessionRelated", because session isn't initialized in there, even if request technically contains session info.
2. If there's no cache entry, Request object is *cloned* and passed to the normal Kernel. Somewhere within that kernel session is initiated and set to SwooleSessionStorage and to Request. Request object is "sessionRelated" now.
3. Request is handled, response is sent.
4. Kernel termination is initiated. But we're out of context of the …
=> Fixed resetting SwooleSessionStorage when Symfony HTTP Cache is used

src/Bridge/Symfony/HttpFoundation/RequestFactory.php
REQUEST_URI could be missing for some invalid/malformed requests (we see it occasionally in production).
When it's missing, accessing undefined array index triggers PHP notice.
This PR ensures that REQUEST_URI defaults to an empty string if not set.
=> Avoid accessing undefined index REQUEST_URI

src/Bridge/Symfony/Bundle/DependencyInjection/CompilerPass/StreamedResponseListenerPass.php, src/Bridge/Symfony/Bundle/Resources/config/services.yaml, src/Bridge/Symfony/Bundle/SwooleBundle.php, src/Bridge/Symfony/HttpFoundation/NoOpStreamedResponseProcessor.php, src/Bridge/Symfony/HttpFoundation/ResponseHeadersAndStatusProcessor.php, src/Bridge/Symfony/HttpFoundation/ResponseProcessor.php, src/Bridge/Symfony/HttpFoundation/StreamedResponseListener.php, src/Bridge/Symfony/HttpFoundation/StreamedResponseProcessor.php, src/Bridge/Symfony/HttpFoundation/SwooleRequestResponseContextManager.php, src/Bridge/Symfony/HttpKernel/HttpKernelRequestHandler.php, tests/Unit/Bridge/Symfony/HttpFoundation/ResponseHeadersAndStatusProcessorTest.php, tests/Unit/Bridge/Symfony/HttpFoundation/ResponseProcessorTest.php, tests/Unit/Bridge/Symfony/HttpFoundation/StreamedResponseProcessorTest.php, tests/Unit/Bridge/Symfony/HttpKernel/HttpKernelHttpDriverTest.php
This PR adds support for StreamedResponse by making use of PHP's output buffering functions.
It's designed to behave as close as possible to original StreamedResponse handling when running Symfony with php-fpm. Compiler pass replaces Symfony's Symfony\Component\HttpKernel\EventListener\StreamedResponseListener with a custom listener, which triggers returning response to the client. The reason listener is used instead of simply calling the response processor from the HttpKernelRequestHandler is the same as originally in Symfony - a callback in StreamedResponse may depend on some services, which depend on Request context (current Request being present in RequestStack). Also error handling that you have in your Symfony app can kick in if the callback fails, which is not the case if we …
=> Add support for StreamedResponse
